'use client';
import { useState, useEffect } from 'react';
import ChevronDown from 'lucide-react/dist/esm/icons/chevron-down';
import ChevronUp from 'lucide-react/dist/esm/icons/chevron-up';
import Printer from 'lucide-react/dist/esm/icons/printer';
import ExternalLink from 'lucide-react/dist/esm/icons/external-link';
import { getCollection, updateItem } from '../../lib/admin-api';
import type { Order, OrderStatus } from '../../types';

const STATUS_COLORS: Record<OrderStatus, string> = {
  pending: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300',
  paid: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300',
  shipped: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
  cancelled: 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300',
};

export default function AdminOrders({ apiKey }: { apiKey: string }) {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const fetchOrders = async () => {
    setLoading(true);
    try {
      const data = await getCollection('orders', apiKey);
      setOrders(Array.isArray(data) ? data : []);
    } catch {
      setOrders([]);
    }
    setLoading(false);
  };

  useEffect(() => { fetchOrders(); }, []);

  const handleStatusChange = async (order: Order, newStatus: OrderStatus) => {
    await updateItem('orders', order.id, { status: newStatus }, apiKey);
    await fetchOrders();
  };

  const handlePrintPackingSlip = (order: Order) => {
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <html>
      <head>
        <title>Packing Slip - #${order.id}</title>
        <style>
          body { font-family: 'Courier New', monospace; padding: 40px; color: #222; }
          h1 { font-size: 24px; border-bottom: 2px solid #222; padding-bottom: 8px; }
          .meta { margin: 16px 0; }
          .meta p { margin: 4px 0; font-size: 14px; }
          table { width: 100%; border-collapse: collapse; margin: 24px 0; }
          th, td { text-align: left; padding: 8px; border-bottom: 1px solid #ddd; font-size: 14px; }
          th { font-weight: bold; border-bottom: 2px solid #222; }
          .total { text-align: right; font-size: 18px; font-weight: bold; margin-top: 16px; }
          .footer { margin-top: 40px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 16px; }
        </style>
      </head>
      <body>
        <h1>Packing Slip</h1>
        <div class="meta">
          <p><strong>Order #${order.id}</strong></p>
          <p>Date: ${new Date(order.createdAt).toLocaleDateString('de-DE', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
          <p>Status: ${order.status.toUpperCase()}</p>
        </div>
        <div class="meta">
          <p><strong>Ship To:</strong></p>
          <p>${order.customer.name}</p>
          <p>${order.customer.address}</p>
          <p>${order.customer.zip} ${order.customer.city}</p>
          <p>${order.customer.email}</p>
        </div>
        <table>
          <tr><th>Qty</th><th>Item</th><th>Options</th><th>Price</th></tr>
          ${order.items.map(item => `
            <tr>
              <td>${item.quantity}x</td>
              <td>${item.name}</td>
              <td>${item.options ? Object.entries(item.options).map(([k, v]) => `${k}: ${v}`).join(', ') : '-'}</td>
              <td>€${item.price.toFixed(2)}</td>
            </tr>
          `).join('')}
        </table>
        <div class="total">Total: €${order.total.toFixed(2)}</div>
        <div class="footer">Generated by Atzengold Admin</div>
        <script>
          window.onload = function() { window.print(); setTimeout(function() { window.close(); }, 1000); };
        <\/script>
      </body>
      </html>
    `);
    win.document.close();
  };

  if (loading) {
    return <p className="text-sm text-ink-secondary dark:text-canvas/60 font-mono">Loading...</p>;
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-black uppercase tracking-tight text-ink dark:text-canvas">Orders</h2>
        <span className="text-xs font-mono text-ink-secondary dark:text-canvas/50">{orders.length} total</span>
      </div>

      {orders.length === 0 && (
        <p className="text-sm text-ink-secondary dark:text-canvas/40 font-mono">No orders yet.</p>
      )}

      <div className="space-y-4">
        {orders.map(order => {
          const isExpanded = expandedId === order.id;
          return (
            <div
              key={order.id}
              className="border border-ink/10 dark:border-canvas/10 rounded-2xl bg-canvas dark:bg-brand-dark-900 overflow-hidden"
            >
              <div className="p-5">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <span className="text-xs font-mono text-ink-secondary dark:text-canvas/50">
                      #{order.id} &middot; {new Date(order.createdAt).toLocaleDateString('de-DE', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
                    </span>
                    <p className="font-bold text-ink dark:text-canvas mt-1">
                      {order.customer.name}
                    </p>
                    <p className="text-xs text-ink-secondary dark:text-canvas/60 font-mono">
                      {order.customer.email} &middot; {order.customer.zip} {order.customer.city}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={`text-xs font-bold px-2.5 py-1 rounded-full capitalize ${STATUS_COLORS[order.status] || ''}`}>
                      {order.status}
                    </span>
                    <select
                      value={order.status}
                      onChange={e => handleStatusChange(order, e.target.value as OrderStatus)}
                      className="text-xs bg-transparent border border-ink/20 dark:border-canvas/20 rounded-lg px-2 py-1 text-ink dark:text-canvas font-mono focus:outline-none focus:border-accent cursor-pointer"
                    >
                      <option value="pending">pending</option>
                      <option value="paid">paid</option>
                      <option value="shipped">shipped</option>
                      <option value="cancelled">cancelled</option>
                    </select>
                    <button
                      onClick={() => setExpandedId(isExpanded ? null : order.id)}
                      className="p-1.5 rounded-lg hover:bg-ink/5 dark:hover:bg-canvas/5 text-ink-secondary dark:text-canvas/60 transition-colors border-none bg-transparent cursor-pointer"
                    >
                      {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                    </button>
                  </div>
                </div>

                <div className="border-t border-ink/5 dark:border-canvas/5 pt-3 space-y-1.5">
                  {order.items.map((item, idx) => (
                    <div key={idx} className="flex justify-between text-sm">
                      <span className="text-ink dark:text-canvas font-medium">
                        {item.quantity}x {item.name}
                        {item.options && Object.entries(item.options).length > 0 && (
                          <span className="text-ink-secondary dark:text-canvas/60 text-xs ml-1">
                            ({Object.entries(item.options).map(([k, v]) => `${k}: ${v}`).join(', ')})
                          </span>
                        )}
                      </span>
                      <span className="text-ink-secondary dark:text-canvas/70 font-mono">€{item.price.toFixed(2)}</span>
                    </div>
                  ))}
                </div>

                <div className="border-t border-ink/5 dark:border-canvas/5 mt-3 pt-3 flex justify-between items-center">
                  <span className="text-xs text-ink-secondary dark:text-canvas/60 font-mono">
                    Subtotal: €{order.subtotal.toFixed(2)} &middot; Shipping: €{order.shipping.toFixed(2)}
                    {order.stripeSessionId && (
                      <span className="ml-2 text-accent">Stripe: {order.stripeSessionId.slice(0, 12)}...</span>
                    )}
                  </span>
                  <span className="text-lg font-black text-ink dark:text-canvas">€{order.total.toFixed(2)}</span>
                </div>
              </div>

              {isExpanded && (
                <div className="border-t border-ink/5 dark:border-canvas/5 bg-ink/[0.02] dark:bg-canvas/[0.02] px-5 py-4 space-y-4">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="text-[10px] uppercase font-mono font-bold text-ink-secondary dark:text-canvas/50 tracking-wider mb-1">Customer</p>
                      <p className="font-bold text-ink dark:text-canvas">{order.customer.name}</p>
                      <p className="text-ink-secondary dark:text-canvas/70">{order.customer.email}</p>
                    </div>
                    <div>
                      <p className="text-[10px] uppercase font-mono font-bold text-ink-secondary dark:text-canvas/50 tracking-wider mb-1">Shipping Address</p>
                      <p className="text-ink dark:text-canvas">{order.customer.address}</p>
                      <p className="text-ink dark:text-canvas">{order.customer.zip} {order.customer.city}</p>
                    </div>
                  </div>

                  <div className="flex gap-2">
                    <button
                      onClick={() => handlePrintPackingSlip(order)}
                      className="flex items-center gap-2 text-xs font-mono font-bold bg-ink dark:bg-accent text-canvas dark:text-on-accent px-4 py-2 rounded-xl hover:bg-zinc-800 dark:hover:bg-accent-hover transition-colors cursor-pointer border-none"
                    >
                      <Printer className="h-4 w-4" />
                      Print Packing Slip
                    </button>
                    {order.stripeSessionId && (
                      <a
                        href={`https://dashboard.stripe.com/payments/${order.stripeSessionId}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-2 text-xs font-mono font-bold bg-accent text-ink px-4 py-2 rounded-xl hover:bg-accent/80 transition-colors"
                      >
                        <ExternalLink className="h-4 w-4" />
                        Stripe Dashboard
                      </a>
                    )}
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
